ARG BUILD_FROM
FROM ${BUILD_FROM}

ENV PUID=0 \
    PGID=0 \
    USER_ID=0 \
    GROUP_ID=0 \
    TZ="Europe/Berlin" \
    ALLOW_DIRECT_VNC="true" \
    LC_ALL="en_US.UTF-8" \
    LANG="en_US.UTF-8" \
    PASSWORD="123456"

EXPOSE 4000 5900
