ARG BUILD_FROM
FROM ${BUILD_FROM}

ENV TZ="Europe/Berlin" \
    FTLCONF_dns_listeningMode="all" \
    FTLCONF_webserver_port="8081" \
    FTLCONF_webserver_api_password="admin" \
    WEBPASSWORD="admin"
