{
  "name": "Tvheadend (Custom)",
  "version": "4.3.2-iCAM",
  "slug": "tvheadend_custom",
  "description": "Tvheadend Server 4.3 ICAM",
  "arch": [
    "aarch64",
    "amd64"
  ],
  "init": false,
  "host_network": true,
  "ingress": false,
  "panel_icon": "mdi:television-play",
  "panel_title": "Tvheadend",
  "webui": "http://[HOST]:[PORT:9981]/",
  "ports": {
    "9981/tcp": 9981,
    "9982/tcp": 9982
  },
  "ports_description": {
    "9981/tcp": "Web Interface",
    "9982/tcp": "HTSP Stream Port"
  },
  "devices": [
    "/dev/dvb"
  ],
  "map": [
    "addon_config:rw",
    "media:rw",
    "share:rw"
  ]
}
